[package]
name = "paillier"
version = "0.1.0"
authors = [
  "Mario Cornejo <mario.cornejo@snips.ai>",
  "Morten Dahl <morten.dahl@snips.ai>"
]
description = "A pure-Rust implementation of the Paillier encryption scheme"
keywords = [
  "Paillier",
  "homomorphic",
  "cryptography",
  "secure-computation",
  "mpc",
]
homepage = "https://github.com/snips/rust-paillier"
repository = "https://github.com/snips/rust-paillier"
license = "MIT/Apache-2.0"

[features]
default = ["inclramp", "defaultramp"]
keygen = ["primal"]
inclramp = ["ramp"]
inclnum = ["num"]
inclgmp = ["rust-gmp"]
defaultramp = []
defaultnum = []
defaultgmp = []

[dependencies]
rand = "0.3"
num-traits = "0.1"
ramp = { git="https://github.com/snipsco/ramp.git", optional=true }
num = { version="0.1", optional=true }
rust-gmp = { version="0.4", optional=true }
primal = { version="0.2", optional=true }

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "encryption"
harness = false

[[bench]]
name = "keygen"
harness = false

[[bench]]
name = "arith"
harness = false

[[bench]]
name = "algo"
harness = false
