[package]
name = "paillier"
version = "0.1.0"
authors = ["Morten Dahl"]
description = "A pure-Rust implementation of the Paillier encryption scheme"
keywords = [
  "Paillier",
  "homomorphic encryption",
  "secure computation",
  "multi-party computation", "MPC",
  "cryptography", "crypto"
]
homepage = "https://github.com/snips/rust-paillier"
repository = "https://github.com/snips/rust-paillier"
license = "MIT/Apache-2.0"

[features]
default = ["inclramp", "defaultramp"]
keygen = ["primal"]
inclramp = ["ramp"]
inclnum = ["num"]
inclgmp = ["rust-gmp"]
defaultramp = []
defaultnum = []
defaultgmp = []

[dependencies]
rand = "0.3"
num-traits = "0.1"
ramp = { version = "0.3", optional = true }
num = { version = "0.1", optional = true }
# rust-gmp = { version = "0.3", optional = true }
rust-gmp = { git = "https://github.com/snipsco/rust-gmp.git", optional = true }
primal = { version = "0.2", optional = true }

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "encryption"
harness = false

[[bench]]
name = "keygen"
harness = false

[[bench]]
name = "arith"
harness = false
