[package]
name = "paillier"
version = "0.2.0-pre"
authors = [
  "Mario Cornejo <mario.cornejo@snips.ai>",
  "Morten Dahl <mortendahlcs@gmail.com>",
  "Mathieu Poumeyrol <mathieu.poumeyrol@snips.ai>"
]
description = "A pure-Rust implementation of the Paillier encryption scheme"
keywords = [
  "paillier",
  "cryptography",
  "homomorphic-encryption",
  "secure-computation",
  "zero-knowledge",
]
homepage = "https://github.com/mortendahl/rust-paillier"
repository = "https://github.com/mortendahl/rust-paillier"
documentation = "https://docs.rs/paillier"
license = "MIT/Apache-2.0"
categories = ["cryptography"]

#[badges]
#travis-ci = { repository = "mortendahl/rust-paillier" }

[features]
default = ["usegmp", "keygen", "proofs"]
keygen = []
proofs = ["ring"]
useramp = ["ramp"]
useframp = ["framp"]
usenum = ["num"]
usegmp = ["rust-gmp"]
gmp_nonsec = []

[dependencies]
rand = "0.3"
num-traits = "0.1"
ramp = { version="0.3", optional=true }
framp = { version="0.3", optional=true }
num = { version="0.1", optional=true }
rust-gmp = { version="0.5", optional=true }
ring = { version="0.12", optional=true }
rayon = "1.0"


[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "proof"
harness = false
